---
title: "TDI Q3: FDA MedWatch Program"
author: "Yitong Li"
date: "11/3/2019"
output: html_document
---


```{r, echo = F}
library(dplyr)
library(lubridate)
library(basicTrendline)
library(ggplot2)
library(plotly)
```

```{r, echo = F}
setwd("~/Documents/Applications/Data Science Fellowship Programs/Data Incubator/TDI Questions")

medwatch = read.csv(file = 'MedWatch The FDA Safety Information and Adverse Event Reporting Program  FDA.csv')

```


```{r, echo = F}

medwatch$Date = as.Date(medwatch$Date, format = '%m/%d/%Y')
medwatch$Year.Month = format(as.Date(medwatch$Date, format = '%Y-%m-%d'), 
                                     '%Y-%m')


agg_medwatch_product = aggregate(medwatch$Safety.Alert, 
                                 by = list(medwatch$Product.Type), 
                                 FUN = function(x) n = length(x))

agg_medwatch_product = do.call(data.frame, agg_medwatch_product)
colnames(agg_medwatch_product) = c('Product.Type', 'Safety.Alert.Counts')
agg_medwatch_product = agg_medwatch_product[order(agg_medwatch_product$Safety.Alert.Counts, decreasing = T),]

#remove unspecified product type
agg_medwatch_product = agg_medwatch_product %>% filter(agg_medwatch_product$Product.Type != '')

agg_medwatch_product_10 = agg_medwatch_product[1:10,]

```


$$\\$$
**Plot 1:**
$$\\$$

```{r, echo = F}

ggplotly(
  ggplot(data = agg_medwatch_product_10, 
       aes( x = Product.Type, y = Safety.Alert.Counts)) + 
  geom_bar(stat = 'identity', position = position_dodge(), 
           color = 'black', size=0.3) + 
  geom_text(aes(label = Safety.Alert.Counts),
            angle = 45, vjust = 0.9,
            position = position_dodge(0.9)) +
  ggtitle('MedWatch Safety Alert Report Jul-2017 to Oct-2019 Top 10') +
  theme_classic()+
  theme( plot.title = element_text(face = 'bold', color = 'black',
                      size = 15, hjust = .5),
         axis.line = element_line(colour = "black", 
                      size = .4, linetype = "solid"),
         axis.text.x =element_text(face="bold", color="black", 
                           size=10, angle = 45, vjust = 0.2),
         axis.text.y = element_text(face="bold", color="black", 
                           size=20, angle = 0),
         axis.ticks.x = element_blank(),
         axis.ticks.y  = element_line(size = 0.6), 
         axis.title.x = element_text(face = 'bold', color = 'black', 
                           size=12, angle = 0), 
         axis.title.y = element_text(face = 'bold', color = 'black', 
                           size=18, angle = 90), 
         legend.title = element_text(face = 'bold', color = 'black',
                           size=18, angle = 0), 
         legend.text = element_text(face = 'bold', color = 'black', 
                           size=10, angle = 0)) +
  xlab(' ') + 
  ylab('Report Count')
  )


```



$$\\$$
**Plot 2:**
$$\\$$
```{r, echo = F}
top1_product = medwatch %>% filter(medwatch$Product.Type == agg_medwatch_product[1,1])

agg_top1_byYM = aggregate(top1_product$Safety.Alert, 
                          by = list(top1_product$Year.Month), 
                          FUN = function(x) n = length(x))
agg_top1_byYM = do.call(data.frame, agg_top1_byYM)
colnames(agg_top1_byYM) = c('Year.Month', 'Safety.Alert.Counts')

ggplotly(
        ggplot(data =  agg_top1_byYM,
               aes(x = Year.Month, y = Safety.Alert.Counts)) +
          geom_line(aes(color= 'black')) +
          geom_point(aes(color= 'black')) + 
          ggtitle('Medical Devices Safety Alert') +
          theme_classic() +
          theme(plot.title = element_text(face = 'bold', hjust = 0.5), 
                axis.text.x = element_text(angle = 45, face = 'bold'),
                axis.text.y = element_text(face = 'bold')) + 
          xlab('Year - Month') +
          ylab('Safety Alerts')
        )
```
